### ISSUE TITLE
Error when click on log-in

### ISSUE THREAD

**Issue by ghost** [maxfarseer/google-sign-in-example#1]
![image](https://user-images.githubusercontent.com/42869116/48135077-8e04e700-e2a4-11e8-87f2-9699f8583ef6.png)

**Comment by maxfarseer** [comment]
Проблема в том, что библиотека порой не успевает инициализироваться. Решения можно посмотреть у некоторых участников из [ревью тз 3](https://maxpfrontend.ru/vebinary/razbor-testovogo-zadaniya-frontend-razrabotchika/)
